name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'v[0-9]+.[0-9]+.[0-9]+-rc*' # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5

jobs:
  artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #build_type: ['build-release-amd64']
        build_type: ['build-release-arm64', 'build-release-amd64']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set version tag
        run: echo "VERSION=$(echo ${{github.ref_name}} | sed 's/^v//')" >> $GITHUB_ENV
      - name: Create build directory
        run: mkdir -p build/release
      - name: Build ${{matrix.build_type}}
        run: make ${{matrix.build_type}}
      - name: Create release for ${{github.ref_name}}
        if: startsWith(github.ref, 'refs/tags/')
        run: gh release create ${{github.ref_name}} ./build/release/* --draft --generate-notes
